# handlers file for alloy
- name: Restart alloy
  listen: "restart alloy"
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: alloy.service
    state: restarted
    enabled: true
    scope: "{{ 'system' if alloy_as_root else 'user' }}"
  environment:
    XDG_RUNTIME_DIR: "{{ '/run/user/' + ansible_user_uid | string if not alloy_as_root else omit }}"
  become: "{{ alloy_as_root }}"
  when: not ansible_check_mode
